### ISSUE TITLE
Library Index documentation is incomplete

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#10200]
### Description
It appears the Index page of the CodeQL classes for a language seems to be incomplete, at least for Java. It does not include all CodeQL classes and predicates. I think it was always incomplete for dataflow related classes, but now it is also missing "regular" classes like `AddExpr`. The classes can still be found with the Search feature, but do not appear on the Index page.

Is this intended?

### Reproduction steps

1. Open https://codeql.github.com/codeql-standard-libraries/java/index.html
2. Try to find `AddExpr` in the list
:x: Bug: It is not in the list
3. Compare this with the archived version of the page: https://web.archive.org/web/20211022203300/https://codeql.github.com/codeql-standard-libraries/java/index.html
✔️ `AddExpr` is in the list

**Comment by Marcono1234** [comment]
Additionally, the list of "Known direct subtypes" seems to be incomplete. For `ConstructorCall` it only [lists `ClassInstanceExpr`](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/Expr.qll/type.Expr$ConstructorCall.html#Known%20direct%20subtypes), even though [`SuperConstructorInvocationStmt` is a subtype as well](https://codeql.github.com/codeql-standard-libraries/java/semmle/code/java/Statement.qll/type.Statement$SuperConstructorInvocationStmt.html#Direct%20supertypes).


Not sure if this is the same underlying issue and whether this problem is actually new or existed previously as well.

**Comment by Marcono1234** [comment]
> It seems this has been fixed.

Is it really? I am still experiencing the missing classes for version 0.4.1.

**Comment by intrigus-lgtm** [comment]
> > It seems this has been fixed.
> 
> Is it really? I am still experiencing the missing classes for version 0.4.1.

I could swear that when I looked at it, this had been fixed.
I'm not 100 percent sure, but I believe I looked at version 0.4.0.

Judging by the `last-modified` header, the site changed on Tue, 11 Oct 2022 18:03:24 GMT.
So it's possible that I indeed looked at a fixed version?
Still, this would not make much sense.
(Why should it be fixed in the previous version, but not the current version???)

**Comment by alexet** [comment]
The documentation generator has been fixed so this should be fixed in the next release.

**Comment by Marcono1234** [comment]
Thanks! The "Known direct subtypes" for `ConstructorCall` seem to be fixed, but the Index still does not list `AddExpr` anymore. Is that intended (given that other similar classes such as `ArrayCreationExpr` are listed)?
